configure: Update with xdp-tools scripts
fix?

Signed-off-by: Štěpán Horáček <shoracek@redhat.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -14,6 +14,7 @@ trap 'status=$?; rm -rf $TMPDIR; rm -f $CONFIG; exit $status' EXIT HUP INT QUIT 
 check_toolchain()
 {
     local emacs_version
+    local clang_version
 
     : ${PKG_CONFIG:=pkg-config}
     : ${CC=gcc}
@@ -21,6 +22,7 @@ check_toolchain()
     : ${LLC=llc}
     : ${M4=m4}
     : ${EMACS=emacs}
+    : ${ARCH_INCLUDES=}
 
     for TOOL in $PKG_CONFIG $CC $CLANG $LLC $M4; do
         if [ ! $(command -v ${TOOL} 2>/dev/null) ]; then
@@ -29,11 +31,18 @@ check_toolchain()
         fi;
     done
 
+    clang_version=$($CLANG --version | grep -Po '(?<=clang version )[[:digit:]]+')
+    echo "Found clang binary '$CLANG' with version $clang_version (from '$($CLANG --version | head -n 1)')"
+    if [ "$clang_version" -lt "10" ]; then
+        echo "*** ERROR: Need LLVM version 10+, '$CLANG' is version $clang_version"
+        [ -n "$RELAXED_LLVM_VERSION" ] || exit 1
+    fi
+
     if ! command -v $EMACS >/dev/null 2>&1; then
         EMACS=""
     else
         emacs_version=$($EMACS --version 2>/dev/null | head -n 1)
-        if echo $emacs_version | grep -Eq 'GNU Emacs 2[67]'; then
+        if echo $emacs_version | grep -Eq 'GNU Emacs 2[6789]'; then
             echo "using emacs: $emacs_version"
         else
             echo "not using emacs: $emacs_version"
@@ -47,12 +56,21 @@ check_toolchain()
         exit 1
     fi
 
+    if [ -z "$ARCH_INCLUDES" ]; then
+        for dir in $(echo | $CC -Wp,-v -E - 2>&1 | grep '^ '); do
+            local idir
+            idir="${dir}/$(uname -m)-linux-gnu/"
+            [ -d "$idir" ] && ARCH_INCLUDES="-I${idir} $ARCH_INCLUDES"
+        done
+    fi
+
     echo "PKG_CONFIG:=${PKG_CONFIG}" >>$CONFIG
     echo "CC:=${CC}" >>$CONFIG
     echo "CLANG:=${CLANG}" >>$CONFIG
     echo "LLC:=${LLC}" >>$CONFIG
     echo "M4:=${M4}" >>$CONFIG
     echo "EMACS:=${EMACS}" >>$CONFIG
+    echo "ARCH_INCLUDES:=$ARCH_INCLUDES" >> $CONFIG
 }
 
 check_elf()
@@ -102,6 +120,21 @@ check_libxdp()
     check_zlib || exit 1
 }
 
+get_libbpf_version()
+{
+    local libbpf_dir
+    local version
+    libbpf_dir="$1"
+
+    if [ -f "${libbpf_dir}/libbpf.map" ]; then
+        version=$(grep -oE '^LIBBPF_([0-9.]+)' "${libbpf_dir}/libbpf.map" | sort -rV | head -n1 | cut -d'_' -f2)
+    else
+        version=unknown
+    fi
+
+    echo $version
+}
+
 check_libbpf()
 {
     local libbpf_err
@@ -111,17 +144,21 @@ check_libbpf()
         if [ -n "$LIBBPF_DIR" ]; then
             LIBBPF_CFLAGS="-I${LIBBPF_DIR}/include -L${LIBBPF_DIR}/lib"
             LIBBPF_LDLIBS="-lbpf"
+            LIBBPF_VERSION=$(get_libbpf_version "$LIBBPF_DIR")
         else
             LIBBPF_CFLAGS=$(${PKG_CONFIG} libbpf --cflags)
             LIBBPF_LDLIBS=$(${PKG_CONFIG} libbpf --libs)
+            LIBBPF_VERSION=$(${PKG_CONFIG} libbpf --modversion)
         fi
 
         cat >$TMPDIR/libbpftest.c <<EOF
 #include <bpf/libbpf.h>
+#include <bpf/bpf.h>
 int main(int argc, char **argv) {
     void *ptr;
     DECLARE_LIBBPF_OPTS(bpf_object_open_opts, opts, .pin_root_path = "/path");
-    DECLARE_LIBBPF_OPTS(bpf_xdp_set_link_opts, lopts, .old_fd = -1);
+    DECLARE_LIBBPF_OPTS(bpf_xdp_set_link_opts, xlopts, .old_fd = -1);
+    DECLARE_LIBBPF_OPTS(bpf_link_create_opts, lopts, .target_btf_id = 0);
     (void) bpf_object__open_file("file", &opts);
     (void) bpf_program__name(ptr);
     (void) bpf_map__set_initial_value(ptr, ptr, 0);
@@ -133,10 +170,11 @@ EOF
         libbpf_err=$($CC -o $TMPDIR/libbpftest $TMPDIR/libbpftest.c  $LIBBPF_CFLAGS -lbpf 2>&1)
         if [ "$?" -eq "0" ]; then
             echo "SYSTEM_LIBBPF:=y" >>$CONFIG
+            echo "LIBBPF_VERSION=$LIBBPF_VERSION" >>$CONFIG
             echo 'CFLAGS += ' $LIBBPF_CFLAGS >> $CONFIG
             echo 'LDLIBS += ' $LIBBPF_LDLIBS >>$CONFIG
             echo 'OBJECT_LIBBPF = ' >>$CONFIG
-            echo system
+            echo "system v$LIBBPF_VERSION"
 
             return 0
         fi
@@ -151,8 +189,10 @@ EOF
         exit 1
     fi
 
-    echo submodule
+    LIBBPF_VERSION=$(get_libbpf_version "lib/libbpf/src")
+    echo "submodule v$LIBBPF_VERSION"
     echo "SYSTEM_LIBBPF:=n" >> $CONFIG
+    echo "LIBBPF_VERSION=$LIBBPF_VERSION" >>$CONFIG
     echo 'CFLAGS += -I$(LIB_DIR)/xdp-tools/lib/libbpf/src/root' >>$CONFIG
     echo 'BPF_CFLAGS += -I$(LIB_DIR)/xdp-tools/lib/libbpf/src/root' >>$CONFIG
     echo 'LDFLAGS += -L$(LIB_DIR)/xdp-tools/lib/libbpf/src' >>$CONFIG
